<form class="formCreate" action="<?= $requestUrl ?>/createaccount" method="post">

    <fieldset>
     <?php // echo $a ?>
      <label for="firtName">Nom : <input type="text" name="nom" value=""></label>
      <label for="lastName">Prénom : <input type="text" name="prenom" value=""></label>
      <label for="mail">Mail : <input type="text" name="mail" value=""></label>
      <label for="mail">Mot de passe : <input type="password" name="mdp" value=""></label>
      <label for="adresse">Adresse : <input type="text" name="adresse" value=""></label>
      <label for="postalCode">Code Postal : <input type="text" name="cp" value=""></label>
      <label for="firtName">Ville : <input type="text" name="ville" value=""></label>
      <button type="submit" name="">Envoyer <i class="fa fa-paper-plane" aria-hidden="true"></i></button>
      <button type="reset" name="button">Annuler <i class="fa fa-trash" aria-hidden="true"></i></button>
    </fieldset>

</form>
