<!-- Message de notification -->

<?php if(isset($flashBag) && $flashBag->hasMessages() == true): ?>
  <?php var_dump($flashBag); ?>
    <aside id="notice" class="notice">
        <?php foreach($flashBag->fetchMessages() as $message): ?>
            <p><?= $message ?></p>
        <?php endforeach ?>
    </aside>
<?php endif; ?>



    <h2>Finalisation de la commande</h2>

<?php
$new_log = new Usersession();
$check_log = $new_log->isAuthenticated();
if($check_log == false){
?>
  <p><a href="<?= $requestUrl ?>/">Retour à l'accueil</a><?php //$_SESSION['panier'] ?></p>

<?php
}else{
?>

<section>
  <h3>Récapitulatif de la commande</h3>

  <table id="recap_panier" class="generic-table">
    <thead>

        <tr>
          <?php foreach ($_SESSION['panier'] as $menus): ?>
                    <?php
                          // $id_menus = array_slice($menus, 0, 1, false);
                          // var_dump($id_menus);
                          // $edit_list = array_slice($menus, 1, null, false);
                          // var_dump($edit_list);
                     ?>
                    <?php foreach ($menus as $key => $value):?>

                              <?php if($key == "quantity"){?>

                                <td class="quantity">

                                    <strong><?= ucfirst($key); ?></strong>

                                </td>
                                <?php
                              } elseif ($key == "id"){?>
                                <td class="hidden">

                                    <strong><?= ucfirst($key); ?>

                                </td>

                                <?php
                                }else{?>
                                <td>

                                    <strong><?= str_replace("_", " ", ucfirst($key)); ?></strong>

                                </td>
                                <?php
                                }?>

                      <?php endforeach;break; //2me foreach?>
          <?php endforeach; // 1er foreach?>
        </tr>
    </thead>
    <tbody id="body_calcul">

            <?php foreach ($_SESSION['panier'] as $menu){ ?>
              <tr>

              <!-- <?php //var_dump($menu); ?> -->

                      <?php
                            // séparation des id du reste du contenu du tableau
                            // $id_menus = array_slice($menus, 0, 1, false);
                            //
                            // $edit_list_product = array_slice($menus, 1, null, false);
                            // var_dump($edit_list);
                       ?>
                      <?php foreach ($menu as $key => $value){?>

                        <?php if($key == "quantity"){
                          ?>
                                <td id="basket_quantity" class="quantity" data-id="<?= $value ?>">
                                          <?= $value ?>
                                </td>
                          <?php
                        } elseif ($key == "id"){?>
                                <td class="hidden">

                                    <?= ucfirst($value); ?>

                                </td>


                          <?php
                        }elseif($key == "tarif"){?>

                                <td class="tarif" data-id="<?= $value ?>" >

                                    <?= ucfirst($value); ?>

                                </td>
                          <?php
                        }else{?>
                                <td>

                                    <?= str_replace("_", " ", ucfirst($value)); ?>
                                </td>
                          <?php
                          }?>

                      <?php } //2me foreach?>

              </tr>

            <?php } // 1er foreach?>
            <tr>
                    <td>
                      Montant total de la commande
                    </td>
                    <td id="resultat">

                    </td>

            </tr>

    </tbody>
  </table>
</section>


<section id="profil">
  <h3>Rappel de vos coordonnées</h3>

  <ul>
    <li>Nom : <?= $_SESSION['nom'] ?></li>
    <li>Prénom : <?= $_SESSION['prenom'] ?></li>
    <li>Mail : <?= $_SESSION['mail'] ?></li>
    <li>Adresse de livraison : <?= $_SESSION['adresse'] ?></li>
    <li>CP : <?= $_SESSION['cp'] ?></li>
    <li>Ville : <?= $_SESSION['ville'] ?></li>
  </ul>

</section>

<a href="<?= $requestUrl ?>/addtobasket/recapbasket" class="button button-primary">Payer</a>
<?php
}?>
