<?php
  if(!isset($_SESSION) && !isset($_SESSION["prenom"])){ ?>

    <p>Bienvenue dans notre restaurant, <a href="<?= $requestUrl ?>/createaccount">inscrivez-vous</a> pour commander !</p>

<?php }else if (isset($_SESSION) && isset($_SESSION["prenom"])){
  // var_dump("SESSION : " . $_SESSION['nom']);

  ?>
  <p>Bonjour <strong><?= $_SESSION['prenom'] ?></strong>, que voulez-vous manger aujourd'hui?</p>

  <?php
    } ?>
<!-- Message de notification -->

<?php if(isset($flashBag) && $flashBag->hasMessages() == true): ?>
  <?php var_dump($flashBag); ?>
    <aside id="notice" class="notice">
        <?php foreach($flashBag->fetchMessages() as $message): ?>
            <p><?= $message ?></p>
        <?php endforeach ?>
    </aside>
<?php endif; ?>
<!-- Code HTML à écrire -->

<?php //var_dump($all_menus); ?>





<!-- Liste des menus -->

<section class="flex liste_menu">
  <?php foreach ($all_menus as $menu) {
    ?>

        <div class="menu_home">
              <h3>Menu <?= $menu["nom_menu"] ?></h3>

              <p>Entrée : <?= $menu["entree"] ?></p>
              <p>Plat : <?= $menu["plat"] ?></p>
              <p>Dessert : <?= $menu["dessert"] ?></p>
              <p>Tarif : <?= $menu["tarif"] ?> €</p>
              <form class="" action="<?= $requestUrl ?>/addtobasket" method="post">
                <input type="hidden" name="id" value="<?= $menu['id'] ?>">
                <select class="" name="quantite">
                  <option value="0">0</option>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                </select>
                <button type="submit" name="">Commander</button>
              </form>
        </div>

  <?php
} ?>

</section>
