<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body class="notice">

<!-- En-tête commune -->
<header>
  <!-- Message de notification -->
  <?php if(isset($flashBag) && $flashBag->hasMessages() == true): ?>
      <aside id="notice" class="notice">
          <?php foreach($flashBag->fetchMessages() as $message): ?>
              <p><?= $message ?></p>
          <?php endforeach ?>
      </aside>
  <?php endif; ?>
    <h1>
        <a href="<?= $requestUrl ?>/">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - la fin des haricots...        </a>
    </h1>
<!-- INCLUSION DE LA NAV-->
              <?php include "partiels/nav_button.phtml" ?>


</header>

<!-- Interface utilisateur -->




<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>

    <?php include "partiels/logAdmin.phtml" ?>


    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/utilities.js"></script>
<script src="<?= $wwwUrl ?>/js/main.js"></script>
<script src="<?= $wwwUrl ?>/js/event.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/formulaire_se_connecter.js"></script>
</body>
</html>
