<?php
$new_log = new Usersession();
$check_log = $new_log->isAuthenticated();

      if($check_log == true){
  ?>
          <a href="<?= $requestUrl ?>/stopsession" id="disconnect" class="linkStart">Se déconnecter</a>
  <?php
      }
      else{
  ?>
          <a href="#" id="connect" class="linkStart">Se connecter</a>
          <a href="<?= $requestUrl ?>/createaccount" id="create_compte" class="linkStart">Créer un compte</a>
  <?php
      }
