<?php
$new_log = new Usersession();
$check_log = $new_log->isAuthenticated();

      if($check_log == true){
  ?>
          <a href="<?= $requestUrl ?>/stopsession" id="disconnect" class="button">Se déconnecter</a>
  <?php
      }
      else{
  ?>
          <a href="#" id="connect" class="button button-primary">Se connecter</a>
          <a href="<?= $requestUrl ?>/createaccount" id="create_compte" class="button button-primary">Créer un compte</a>
  <?php
      }
