<?php
$new_log = new Usersession();
$check_log = $new_log->isAuthenticated();
// var_dump($check_log);
if($check_log == true){
      if($_SESSION['user'] == 1){ // Si c'est un client
  ?>
    <nav class="user-interface">
        <ul class="link-list">
            <!-- Code HTML/PHP à écrire -->
            <li><a href="<?= $requestUrl ?>/" class="button button-primary">Home</a></li>
            <li><a href="#" class="button button-primary">Menu</a></li>
            <li><a href="#" class="button button-primary">Accès</a></li>
            <li><a href="<?= $requestUrl ?>/loginclient" class="button button-primary">Mon Compte</a></li>
            <li id="bloc_connect">
              <?php include "alternative_button.phtml" ?>
            </li>
            <li><a href="<?= $requestUrl ?>/addtobasket/basketlist" class="button button-primary"><?= !isset($_SESSION['total_quantity'])? 0 : $_SESSION['total_quantity']; ?> <i class="fa fa-shopping-cart" aria-hidden="true"></i></a></li>
        </ul>
    </nav>
 <form class="hidden formConnect generic-form" action="<?= $requestUrl ?>/loginclient" method="post">
       <label for="mail">Mail : <input type="text" name="mail" value=""></label>
       <label for="mdp">Mot de passe : <input type="password" name="mdp" value=""></label>
       <button type="submit" name="" class="button button-primary">Se connecter >></button>
       <button type="reset" name="" class="button button-cancel">Annuler</button>

 </form>
 <?php }elseif($_SESSION['user'] == 2){ // Si c'est un salarié?>

   <nav class="admin-interface">
       <ul class="link-list">
           <!-- Code HTML/PHP à écrire -->
           <li><a href="<?= $requestUrl ?>/loginemployee" class="button button-primary">Accueil Admin</a></li>
           <li><a href="<?= $requestUrl ?>/listemenu" class="button button-primary">Liste Menu</a></li>
           <li><a href="<?= $requestUrl ?>/liste_commandes" class="button button-primary">Liste Commandes</a></li>
           <li id="bloc_connect">
             <?php include "alternative_button.phtml" ?>
           </li>
       </ul>
   </nav>

 <?php }
}else{// si personne n'est identifié
  ?>
  <nav class="user-interface">
      <ul class="link-list">
          <!-- Code HTML/PHP à écrire -->
          <li><a href="<?= $requestUrl ?>/" class="button button-primary">Home</a></li>
          <li><a href="#" class="button button-primary">Menu</a></li>
          <li><a href="#" class="button button-primary">Accès</a></li>
          <li id="bloc_connect">
            <a href="#" id="connect" class="button button-primary">Se connecter</a>
            <a href="<?= $requestUrl ?>/createaccount" id="create_compte" class="button button-primary">Créer un compte</a>
          </li>
          <li><a href="<?= $requestUrl ?>/addtobasket/basketlist" class="button button-primary"><?= $panier = 0 ?> <i class="fa fa-shopping-cart" aria-hidden="true"></i></a></li>
      </ul>
  </nav>
<form class="hidden formConnect" action="<?= $requestUrl ?>/loginclient" method="post">
     <label for="mail">Mail : <input type="text" name="mail" value=""></label>
     <label for="mdp">Mot de passe : <input type="password" name="mdp" value=""></label>
     <button type="submit" name="" class="button button-primary">Se connecter >></button>
     <button type="reset" name="" class="button button-cancel">Annuler</button>
</form>

<?php } ?>
