<?php
if(isset($_SESSION)){
    if(!array_key_exists('type', $_SESSION)){ // Si c'est un client
  ?>
    <nav class="user-interface">
        <ul class="link-list">
            <!-- Code HTML/PHP à écrire -->
            <li><a href="<?= $requestUrl ?>">Home</a></li>
            <li><a href="#">Menu</a></li>
            <li><a href="#">Accès</a></li>
            <li id="bloc_connect">
              <?php include "alternative_button.phtml" ?>
            </li>
        </ul>
    </nav>
 <form class="hidden formConnect" action="<?= $requestUrl ?>/loginclient" method="post">
       <label for="mail">Mail : <input type="text" name="mail" value=""></label>
       <label for="mdp">Mot de passe : <input type="text" name="mdp" value=""></label>
       <button type="submit" name="">Se connecter >></button>
       <button type="reset" name="">Annuler</button>

 </form>
 <?php }else{ // Si c'est un salarié?>

   <nav class="admin-interface">
       <ul class="link-list">
           <!-- Code HTML/PHP à écrire -->
           <li><a href="<?= $requestUrl ?>/loginemployee">Accueil Admin</a></li>
           <li><a href="<?= $requestUrl ?>/listemenu">Liste Menu</a></li>
           <li><a href="<?= $requestUrl ?>/liste_commandes">Liste Commandes</a></li>
           <li id="bloc_connect">
             <?php include "alternative_button.phtml" ?>
           </li>
       </ul>
   </nav>

 <?php }
}else{// si personne n'est identifié
  ?>
  <nav class="user-interface">
      <ul class="link-list">
          <!-- Code HTML/PHP à écrire -->
          <li><a href="<?= $requestUrl ?>">Home</a></li>
          <li><a href="#">Menu</a></li>
          <li><a href="#">Accès</a></li>
          <li id="bloc_connect">
            <?php include "alternative_button.phtml" ?>
          </li>
      </ul>
  </nav>
<form class="hidden formConnect" action="<?= $requestUrl ?>/loginclient" method="post">
     <label for="mail">Mail : <input type="text" name="mail" value=""></label>
     <label for="mdp">Mot de passe : <input type="text" name="mdp" value=""></label>
     <button type="submit" name="">Se connecter >></button>
     <button type="reset" name="">Annuler</button>
</form>

<?php } ?>
