<!-- Liste des menus -->
<section class="flex liste_menu">

  <?php foreach ($all_menus as $menu) {
  ?>

        <div class="menu_home">
              <h3>Menu <?= $menu["nom_menu"] ?></h3>

              <p>Entrée : <?= $menu["entree"] ?></p>
              <p>Plat : <?= $menu["plat"] ?></p>
              <p>Dessert : <?= $menu["dessert"] ?></p>
              <p>Tarif : <?= $menu["tarif"] ?> €</p>
              <a href="<?= $requestUrl ?>/addtobasket" class="bouton_commande" data-id="<?= $menu["id"] ?>" data-tarif="<?= $menu["tarif"] ?>">Commander</a>

        </div>

  <?php
  }
  ?>

</section>
